In [ ]:
import numpy as np
import pandas as pd

# Cut, Qcut

In [ ]:
df = pd.read_csv('university.csv',usecols = ['university','rank', 'overall_score', 'employment_outcomes'], index_col='university')
df.head()

,rank,overall_score,employment_outcomes
university,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0
University of Cambridge,2,99.2,100.0
University of Oxford,3,98.9,100.0
Harvard University,4,98.3,100.0
Stanford University,5,98.1,100.0

In [ ]:
df.shape

(105, 3)

In [ ]:
df.overall_score.describe()

count    105.000000
mean      75.016190
std       11.454501
min       59.400000
25%       64.700000
50%       73.400000
75%       84.500000
max      100.000000
Name: overall_score, dtype: float64

In [ ]:
bins = [50,70,80,90,100]
score = pd.cut(df.overall_score,bins)
score

university
Massachusetts Institute of Technology (MIT)       (90, 100]
University of Cambridge                           (90, 100]
University of Oxford                              (90, 100]
Harvard University                                (90, 100]
Stanford University                               (90, 100]
                                                    ...
University of Nottingham                           (50, 70]
University of Wisconsin-Madison                    (50, 70]
Pontificia Universidad CatÃ³lica de Chile (UC)     (50, 70]
The University of Sheffield                        (50, 70]
Uppsala University                                 (50, 70]
Name: overall_score, Length: 105, dtype: category
Categories (4, interval[int64, right]): [(50, 70] < (70, 80] < (80, 90] < (90, 100]]

In [ ]:
score.value_counts()

(50, 70]     44
(70, 80]     25
(80, 90]     25
(90, 100]    11
Name: overall_score, dtype: int64

In [ ]:
df['ovscore_bins'] = score
df.sample(7)

,rank,overall_score,employment_outcomes,ovscore_bins
university,,,,
The University of Queensland,43,78.1,44.4,"(70, 80]"
Australian National University (ANU),34,81.5,43.9,"(80, 90]"
Osaka University,80,63.9,23.4,"(50, 70]"
Cornell University,13,89.3,98.0,"(80, 90]"
Universidad de Buenos Aires (UBA),95,61.0,26.2,"(50, 70]"
University of Texas at Austin,58,71.8,70.0,"(70, 80]"
Universidade de SÃ£o Paulo,85,62.8,89.7,"(50, 70]"

In [ ]:
df.employment_outcomes.describe()

count    105.000000
mean      63.664762
std       27.323877
min       13.400000
25%       39.600000
50%       66.000000
75%       92.500000
max      100.000000
Name: employment_outcomes, dtype: float64

In [ ]:
bins = [10,30,50,70,90,100]
emp = pd.cut(df.employment_outcomes,bins)
emp

university
Massachusetts Institute of Technology (MIT)       (90, 100]
University of Cambridge                           (90, 100]
University of Oxford                              (90, 100]
Harvard University                                (90, 100]
Stanford University                               (90, 100]
                                                    ...
University of Nottingham                           (10, 30]
University of Wisconsin-Madison                    (70, 90]
Pontificia Universidad CatÃ³lica de Chile (UC)     (70, 90]
The University of Sheffield                        (10, 30]
Uppsala University                                 (50, 70]
Name: employment_outcomes, Length: 105, dtype: category
Categories (5, interval[int64, right]): [(10, 30] < (30, 50] < (50, 70] < (70, 90] < (90, 100]]

In [ ]:
df['emp_range'] = emp
df

,rank,overall_score,employment_outcomes,ovscore_bins,emp_range
university,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,"(90, 100]",prestigious
University of Cambridge,2,99.2,100.0,"(90, 100]",prestigious
University of Oxford,3,98.9,100.0,"(90, 100]",prestigious
Harvard University,4,98.3,100.0,"(90, 100]",prestigious
Stanford University,5,98.1,100.0,"(90, 100]",prestigious
...,...,...,...,...,...
University of Nottingham,100,60.4,24.4,"(50, 70]",bad
University of Wisconsin-Madison,102,60.0,73.1,"(50, 70]",excelent
Pontificia Universidad CatÃ³lica de Chile (UC),103,59.9,76.3,"(50, 70]",excelent
The University of Sheffield,104,59.7,24.9,"(50, 70]",bad
Uppsala University,105,59.4,58.2,"(50, 70]",good

In [ ]:
name = ['bad', 'average', 'good', 'excelent', 'prestigious' ]
emp = pd.cut(df.employment_outcomes,bins, labels=name)
emp.value_counts()

prestigious    28
average        22
good           20
excelent       18
bad            17
Name: employment_outcomes, dtype: int64

In [ ]:
df['emp_range'] = emp
df

,rank,overall_score,employment_outcomes,ovscore_bins,emp_range
university,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,"(90, 100]",prestigious
University of Cambridge,2,99.2,100.0,"(90, 100]",prestigious
University of Oxford,3,98.9,100.0,"(90, 100]",prestigious
Harvard University,4,98.3,100.0,"(90, 100]",prestigious
Stanford University,5,98.1,100.0,"(90, 100]",prestigious
...,...,...,...,...,...
University of Nottingham,100,60.4,24.4,"(50, 70]",bad
University of Wisconsin-Madison,102,60.0,73.1,"(50, 70]",excelent
Pontificia Universidad CatÃ³lica de Chile (UC),103,59.9,76.3,"(50, 70]",excelent
The University of Sheffield,104,59.7,24.9,"(50, 70]",bad
Uppsala University,105,59.4,58.2,"(50, 70]",good

In [ ]:
df[df.emp_range == 'prestigious']

,rank,overall_score,employment_outcomes,ovscore_bins,emp_range
university,,,,,
Massachusetts Institute of Technology (MIT),1,100.0,100.0,"(90, 100]",prestigious
University of Cambridge,2,99.2,100.0,"(90, 100]",prestigious
University of Oxford,3,98.9,100.0,"(90, 100]",prestigious
Harvard University,4,98.3,100.0,"(90, 100]",prestigious
Stanford University,5,98.1,100.0,"(90, 100]",prestigious
National University of Singapore (NUS),8,92.7,100.0,"(90, 100]",prestigious
"University of California, Berkeley (UCB)",10,90.4,98.7,"(90, 100]",prestigious
University of Chicago,11,90.3,98.3,"(90, 100]",prestigious
University of Pennsylvania,12,89.4,100.0,"(80, 90]",prestigious
Cornell University,13,89.3,98.0,"(80, 90]",prestigious
The University of Melbourne,14,87.9,93.3,"(80, 90]",prestigious
Yale University,16,87.7,99.9,"(80, 90]",prestigious
Princeton University,17,87.0,94.6,"(80, 90]",prestigious
The University of New South Wales (UNSW Sydney),19,86.7,95.5,"(80, 90]",prestigious
University of Toronto,21,86.3,96.4,"(80, 90]",prestigious
Columbia University,23,85.9,99.9,"(80, 90]",prestigious
The University of Hong Kong,26,84.5,99.5,"(80, 90]",prestigious
The University of Tokyo,28,84.3,99.8,"(80, 90]",prestigious
"University of California, Los Angeles (UCLA)",29,83.8,97.0,"(80, 90]",prestigious
McGill University,30,83.7,92.5,"(80, 90]",prestigious
University of Michigan-Ann Arbor,33,81.7,94.3,"(80, 90]",prestigious
Institut Polytechnique de Paris,38,79.5,90.3,"(70, 80]",prestigious
New York University (NYU),38,79.5,99.7,"(70, 80]",prestigious
Seoul National University,41,78.5,100.0,"(70, 80]",prestigious
The London School of Economics and Political Science (LSE),45,76.9,98.6,"(70, 80]",prestigious
Northwestern University,47,76.2,97.7,"(70, 80]",prestigious
The University of Auckland,68,68.0,94.3,"(50, 70]",prestigious
National Taiwan University (NTU),69,67.9,99.7,"(50, 70]",prestigious

In [ ]:
emp = pd.cut(df.employment_outcomes, 5)
emp.value_counts()

(82.68, 100.0]     32
(65.36, 82.68]     22
(13.313, 30.72]    18
(48.04, 65.36]     17
(30.72, 48.04]     16
Name: employment_outcomes, dtype: int64

In [ ]:
 # if equally divided
emp = pd.qcut(df.employment_outcomes, 5)
emp.value_counts()

(13.399000000000001, 34.38]    21
(34.38, 53.32]                 21
(53.32, 72.38]                 21
(72.38, 95.68]                 21
(95.68, 100.0]                 21
Name: employment_outcomes, dtype: int64

# groupby

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [ ]:
df.groupby('company').mean()

<ipython-input-3-68a802e890b6>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('company').mean()

,wheel-base,length,horsepower,average-mileage,price
company,,,,,
alfa-romero,90.566667,169.600000,125.333333,20.333333,15498.333333
audi,101.200000,180.800000,109.250000,20.000000,16392.500000
bmw,103.433333,185.033333,144.833333,19.000000,27213.333333
chevrolet,92.466667,151.933333,62.666667,41.000000,6007.000000
dodge,93.700000,157.300000,68.000000,31.000000,6303.000000
honda,96.500000,167.200000,92.333333,26.333333,10195.000000
isuzu,94.433333,160.833333,72.666667,33.333333,6785.000000
jaguar,109.333333,196.966667,204.666667,14.333333,34600.000000
mazda,95.900000,164.260000,75.400000,28.000000,9654.800000
mercedes-benz,113.225000,197.275000,153.500000,18.000000,35040.000000
mitsubishi,95.000000,164.850000,78.000000,29.500000,6689.000000
nissan,95.680000,170.140000,82.800000,31.400000,8289.000000
porsche,92.466667,171.166667,234.000000,17.000000,35528.000000
toyota,96.957143,167.571429,75.428571,28.714286,8216.857143
volkswagen,97.300000,171.700000,72.250000,31.750000,8435.000000
volvo,104.300000,188.800000,114.000000,23.000000,13177.500000

In [ ]:
df.groupby('company').price.max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

In [ ]:
df.groupby(['company', 'body-style']).mean()

<ipython-input-5-696145c5feba>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['company', 'body-style']).mean()

                           wheel-base      length  horsepower  \
company       body-style
alfa-romero   convertible   88.600000  168.800000  111.000000
              hatchback     94.500000  171.200000  154.000000
audi          sedan         99.666667  176.833333  109.000000
              wagon        105.800000  192.700000  110.000000
bmw           sedan        103.433333  185.033333  144.833333
chevrolet     hatchback     91.450000  148.500000   59.000000
              sedan         94.500000  158.800000   70.000000
dodge         hatchback     93.700000  157.300000   68.000000
honda         sedan         96.500000  172.250000  100.500000
              wagon         96.500000  157.100000   76.000000
isuzu         sedan         94.433333  160.833333   72.666667
jaguar        sedan        109.333333  196.966667  204.666667
mazda         hatchback     93.650000  161.575000   76.250000
              sedan        104.900000  175.000000   72.000000
mercedes-benz hardtop      112.000000  199.200000  184.000000
              sedan        115.450000  199.500000  153.500000
              wagon        110.000000  190.900000  123.000000
mitsubishi    hatchback     93.700000  157.300000   68.000000
              sedan         96.300000  172.400000   88.000000
nissan        sedan         95.975000  170.125000   86.250000
              wagon         94.500000  170.200000   69.000000
porsche       convertible   89.500000  168.900000  207.000000
              hardtop       89.500000  168.900000  207.000000
              hatchback     98.400000  175.700000  288.000000
toyota        hatchback     95.700000  158.700000   62.000000
              wagon         97.900000  174.225000   85.500000
volkswagen    sedan         97.300000  171.700000   72.250000
volvo         sedan        104.300000  188.800000  114.000000
              wagon        104.300000  188.800000  114.000000

                           average-mileage         price
company       body-style
alfa-romero   convertible        21.000000  14997.500000
              hatchback          19.000000  16500.000000
audi          sedan              20.333333  15550.000000
              wagon              19.000000  18920.000000
bmw           sedan              19.000000  27213.333333
chevrolet     hatchback          42.500000   5723.000000
              sedan              38.000000   6575.000000
dodge         hatchback          31.000000   6303.000000
honda         sedan              24.500000  11645.000000
              wagon              30.000000   7295.000000
isuzu         sedan              33.333333   6785.000000
jaguar        sedan              14.333333  34600.000000
mazda         hatchback          27.250000   7482.500000
              sedan              31.000000  18344.000000
mercedes-benz hardtop            14.000000  45400.000000
              sedan              18.000000  33256.000000
              wagon              22.000000  28248.000000
mitsubishi    hatchback          34.000000   5789.000000
              sedan              25.000000   7589.000000
nissan        sedan              31.500000   8524.000000
              wagon              31.000000   7349.000000
porsche       convertible        17.000000  37028.000000
              hardtop            17.000000  34028.000000
              hatchback          17.000000           NaN
toyota        hatchback          32.333333   6058.000000
              wagon              26.000000   9836.000000
volkswagen    sedan              31.750000   8435.000000
volvo         sedan              23.000000  12940.000000
              wagon              23.000000  13415.000000

In [ ]:
df.groupby('company').max()

,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
company,,,,,,,,
alfa-romero,hatchback,94.5,171.2,ohcv,six,154,21,16500.0
audi,wagon,105.8,192.7,ohc,four,115,24,18920.0
bmw,sedan,110.0,197.0,ohc,six,182,23,41315.0
chevrolet,sedan,94.5,158.8,ohc,three,70,47,6575.0
dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
honda,wagon,96.5,175.4,ohc,four,101,30,12945.0
isuzu,sedan,94.5,170.7,ohc,four,78,38,6785.0
jaguar,sedan,113.0,199.6,ohcv,twelve,262,15,36000.0
mazda,sedan,104.9,175.0,rotor,two,101,31,18344.0
mercedes-benz,wagon,120.9,208.1,ohcv,five,184,22,45400.0
mitsubishi,sedan,96.3,172.4,ohc,four,88,37,8189.0
nissan,wagon,100.4,184.6,ohcv,six,152,45,13499.0
porsche,hatchback,98.4,175.7,ohcf,six,288,17,37028.0
toyota,wagon,104.5,187.8,ohc,six,156,35,15750.0
volkswagen,sedan,97.3,171.7,ohc,four,100,37,9995.0
volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.groupby('company').agg([len,min,max])

              body-style                         wheel-base                \
                     len          min        max        len    min    max
company
alfa-romero            3  convertible  hatchback          3   88.6   94.5
audi                   4        sedan      wagon          4   99.4  105.8
bmw                    6        sedan      sedan          6  101.2  110.0
chevrolet              3    hatchback      sedan          3   88.4   94.5
dodge                  2    hatchback  hatchback          2   93.7   93.7
honda                  3        sedan      wagon          3   96.5   96.5
isuzu                  3        sedan      sedan          3   94.3   94.5
jaguar                 3        sedan      sedan          3  102.0  113.0
mazda                  5    hatchback      sedan          5   93.1  104.9
mercedes-benz          4      hardtop      wagon          4  110.0  120.9
mitsubishi             4    hatchback      sedan          4   93.7   96.3
nissan                 5        sedan      wagon          5   94.5  100.4
porsche                3  convertible  hatchback          3   89.5   98.4
toyota                 7    hatchback      wagon          7   95.7  104.5
volkswagen             4        sedan      sedan          4   97.3   97.3
volvo                  2        sedan      wagon          2  104.3  104.3

              length               engine-type  ... num-of-cylinders  \
                 len    min    max         len  ...              max
company                                         ...
alfa-romero        3  168.8  171.2           3  ...              six
audi               4  176.6  192.7           4  ...             four
bmw                6  176.8  197.0           6  ...              six
chevrolet          3  141.1  158.8           3  ...            three
dodge              2  157.3  157.3           2  ...             four
honda              3  157.1  175.4           3  ...             four
isuzu              3  155.9  170.7           3  ...             four
jaguar             3  191.7  199.6           3  ...           twelve
mazda              5  159.1  175.0           5  ...              two
mercedes-benz      4  190.9  208.1           4  ...             five
mitsubishi         4  157.3  172.4           4  ...             four
nissan             5  165.3  184.6           5  ...              six
porsche            3  168.9  175.7           3  ...              six
toyota             7  158.7  187.8           7  ...              six
volkswagen         4  171.7  171.7           4  ...             four
volvo              2  188.8  188.8           2  ...             four

              horsepower           average-mileage         price           \
                     len  min  max             len min max   len      min
company
alfa-romero            3  111  154               3  19  21     3  13495.0
audi                   4  102  115               4  18  24     4  13950.0
bmw                    6  101  182               6  15  23     6  16430.0
chevrolet              3   48   70               3  38  47     3   5151.0
dodge                  2   68   68               2  31  31     2   6229.0
honda                  3   76  101               3  24  30     3   7295.0
isuzu                  3   70   78               3  24  38     3   6785.0
jaguar                 3  176  262               3  13  15     3  32250.0
mazda                  5   68  101               5  17  31     5   5195.0
mercedes-benz          4  123  184               4  14  22     4  25552.0
mitsubishi             4   68   88               4  25  37     4   5389.0
nissan                 5   55  152               5  19  45     5   6649.0
porsche                3  207  288               3  17  17     3  34028.0
toyota                 7   62  156               7  19  35     7   5348.0
volkswagen             4   52  100               4  26  37     4   7775.0
volvo                  2  114  114               2  23  23     2  12940.0


                   max
company
alfa-romero    16500.0
audi           18920.0
bmw            41315.0
chevrolet       6575.0
dodge           6377.0
honda          12945.0
isuzu           6785.0
jaguar         36000.0
mazda          18344.0
mercedes-benz  45400.0
mitsubishi      8189.0
nissan         13499.0
porsche        37028.0
toyota         15750.0
volkswagen      9995.0
volvo          13415.0

[16 rows x 24 columns]

In [ ]:
df.groupby('company').price.agg([min,max,np.mean])

                   min      max          mean
company
alfa-romero    13495.0  16500.0  15498.333333
audi           13950.0  18920.0  16392.500000
bmw            16430.0  41315.0  27213.333333
chevrolet       5151.0   6575.0   6007.000000
dodge           6229.0   6377.0   6303.000000
honda           7295.0  12945.0  10195.000000
isuzu           6785.0   6785.0   6785.000000
jaguar         32250.0  36000.0  34600.000000
mazda           5195.0  18344.0   9654.800000
mercedes-benz  25552.0  45400.0  35040.000000
mitsubishi      5389.0   8189.0   6689.000000
nissan          6649.0  13499.0   8289.000000
porsche        34028.0  37028.0  35528.000000
toyota          5348.0  15750.0   8216.857143
volkswagen      7775.0   9995.0   8435.000000
volvo          12940.0  13415.0  13177.500000

In [ ]:
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [ ]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [ ]:
bins = [5000,10000,20000,30000,40000]
labels = ['cheap', 'average', 'expensive', 'costly']
df['price_labels'] = pd.cut(df.price, bins, labels=labels)
df

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price,price_labels
index,,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0,average
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0,average
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0,average
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0,average
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0,average
...,...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0,cheap
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0,cheap
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0,cheap
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0,average
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0,average

# Random

In [ ]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/MOCK_USER_DATA.csv", index_col=0)
df.head()

   first_name   last_name                           email       gender   age
id
1     Dorothy     Verryan               dverryan0@who.int   Non-binary     1
2     Pietrek     Scanlin          pscanlin1@yolasite.com         Male    91
3      Lilith    Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
4        Knox  Cunningham    kcunningham3@yellowpages.com  Genderfluid     6
5    Mohammed  Habbershon    mhabbershon4@sourceforge.net       Female    48

In [ ]:
df.age.describe()

count     100.000000
mean      145.660000
std       565.631411
min       -85.000000
25%        22.750000
50%        53.500000
75%        84.250000
max      4444.000000
Name: age, dtype: float64

In [ ]:
df[(df.age > 123) | (df.age < 0)]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
11      Elijah      Heine                eheinea@imdb.com     Bigender   -85
19       Luisa  Bradborne            lbradbornei@fema.gov       Female   -75
21       Levin     Worner                lwornerk@ihg.com  Genderqueer   -43
33    Ebenezer    Greeves           egreevesw@myspace.com         Male   -26
38        Hana   Langwade  hlangwade11@washingtonpost.com  Genderqueer   -42
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
90   Zachariah      Meins            zmeins2h@weather.com         Male   -69
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

In [ ]:
df.age.apply(np.abs)

id
1         1
2        91
3      1233
4         6
5        48
       ...
96       64
97       18
98       55
99       46
100     233
Name: age, Length: 100, dtype: int64

In [ ]:
df.age = df.age.apply(np.abs)
df[df.age > 123]

    first_name  last_name                           email       gender   age
id
3       Lilith   Sarjeant  lsarjeant2@creativecommons.org  Genderfluid  1233
39      Godard      Miere               gmiere12@1688.com   Polygender  3434
47       Cleve  Sparshatt      csparshatt1a@economist.com  Genderfluid   333
49       Trace   Stockney          tstockney1c@flavors.me       Female   344
65      Eloise    Snoddon    esnoddon1s@elegantthemes.com  Genderfluid   332
80       Gabie     Rothon              grothon27@ehow.com  Genderqueer  4444
100      Mable    Toffano          mtoffano2r@myspace.com     Bigender   233

In [ ]:
idx = df[df.age > 123].index
idx

Int64Index([3, 39, 47, 49, 65, 80, 100], dtype='int64', name='id')

In [ ]:
df.drop(index=idx,inplace=True)
df.age.describe() # logically true

count     93.000000
mean      52.612903
std       29.978265
min        1.000000
25%       29.000000
50%       52.000000
75%       77.000000
max      100.000000
Name: age, dtype: float64

In [ ]:
df.gender # Only man and female depending on your choice

id
1      Non-binary
2            Male
4     Genderfluid
5          Female
6     Genderfluid
         ...
95     Non-binary
96        Agender
97         Female
98       Bigender
99    Genderfluid
Name: gender, Length: 93, dtype: object

In [ ]:
df = df[df.gender.isin(['Male', 'Female'])]
df

   first_name     last_name                         email  gender  age
id
2     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
5    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
10      David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
12  Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
17      Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
19      Luisa     Bradborne          lbradbornei@fema.gov  Female   75
22        Ray         Padly           rpadlyl@twitpic.com    Male   85
26   Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
29      Biron      Acklands        backlandss@comsenz.com    Male   13
33   Ebenezer       Greeves         egreevesw@myspace.com    Male   26
34     Brooks          Vose             bvosex@amazon.com  Female   34
36        Axe       Arundel           aarundelz@yahoo.com  Female   14
43       Bili     Swetenham        bswetenham16@europa.eu    Male   23
46     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
58     Brynna        Worsom              bworsom1l@wp.com    Male   66
61       Page       Merrell     pmerrell1o@slideshare.net    Male    1
62     Kennan         Visco          kvisco1p@jiathis.com  Female   94
63   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
67     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
70      Ambur        Aickin           aaickin1x@about.com    Male   60
72   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
74      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
76      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
77     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
81       Alex         Darth    adarth28@ezinearticles.com  Female   98
86    Rogerio          Akid           rakid2d@latimes.com  Female    3
87      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
88       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
90  Zachariah         Meins          zmeins2h@weather.com    Male   69
91      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
94     Sheree        Cockin     scockin2l@accuweather.com  Female   94
97     Kattie       Claxson        kclaxson2o@booking.com  Female   18

In [ ]:
df.index = range(32)

In [ ]:
df

   first_name     last_name                         email  gender  age
0     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
1    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
2       David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
3   Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
4       Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
5       Luisa     Bradborne          lbradbornei@fema.gov  Female   75
6         Ray         Padly           rpadlyl@twitpic.com    Male   85
7    Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
8       Biron      Acklands        backlandss@comsenz.com    Male   13
9    Ebenezer       Greeves         egreevesw@myspace.com    Male   26
10     Brooks          Vose             bvosex@amazon.com  Female   34
11        Axe       Arundel           aarundelz@yahoo.com  Female   14
12       Bili     Swetenham        bswetenham16@europa.eu    Male   23
13     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
14     Brynna        Worsom              bworsom1l@wp.com    Male   66
15       Page       Merrell     pmerrell1o@slideshare.net    Male    1
16     Kennan         Visco          kvisco1p@jiathis.com  Female   94
17   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
18     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
19      Ambur        Aickin           aaickin1x@about.com    Male   60
20   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
21      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
22      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
23     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
24       Alex         Darth    adarth28@ezinearticles.com  Female   98
25    Rogerio          Akid           rakid2d@latimes.com  Female    3
26      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
27       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
28  Zachariah         Meins          zmeins2h@weather.com    Male   69
29      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
30     Sheree        Cockin     scockin2l@accuweather.com  Female   94
31     Kattie       Claxson        kclaxson2o@booking.com  Female   18

In [ ]:
randlist = np.random.permutation(32)
randlist

array([11, 18, 22, 15, 12, 27, 16, 21,  7, 25, 14,  4, 10,  0, 13, 17, 20,
        5,  1,  2,  9, 26,  3,  8, 28, 19, 29, 30, 31, 24, 23,  6])

In [ ]:
df.take(randlist)

   first_name     last_name                         email  gender  age
11        Axe       Arundel           aarundelz@yahoo.com  Female   14
18     Bunnie        Ozanne      bozanne1u@whitehouse.gov    Male   92
22      Misty         Blanc         mblanc23@amazon.co.jp    Male   74
15       Page       Merrell     pmerrell1o@slideshare.net    Male    1
12       Bili     Swetenham        bswetenham16@europa.eu    Male   23
27       Kain     Dumphries  kdumphries2f@hugedomains.com    Male   93
16     Kennan         Visco          kvisco1p@jiathis.com  Female   94
21      Curry    Smalecombe  csmalecombe21@washington.edu    Male   69
7    Ephrayim    Westmacott         ewestmacottp@ning.com    Male   77
25    Rogerio          Akid           rakid2d@latimes.com  Female    3
14     Brynna        Worsom              bworsom1l@wp.com    Male   66
4       Byram   Martynikhin     bmartynikhing@jiathis.com    Male   40
10     Brooks          Vose             bvosex@amazon.com  Female   34
0     Pietrek       Scanlin        pscanlin1@yolasite.com    Male   91
13     Alvira  Stollsteiner     astollsteiner19@mysql.com    Male   66
17   Adrianne       Gommowe  agommowe1q@deliciousdays.com    Male  100
20   Eleanora       Kamenar       ekamenar1z@examiner.com    Male   47
5       Luisa     Bradborne          lbradbornei@fema.gov  Female   75
1    Mohammed    Habbershon  mhabbershon4@sourceforge.net  Female   48
2       David      Meredyth    dmeredyth9@telegraph.co.uk  Female   68
9    Ebenezer       Greeves         egreevesw@myspace.com    Male   26
26      Peder        Murrie       pmurrie2e@bloglovin.com    Male   69
3   Raffaello     Firminger     rfirmingerb@bloomberg.com  Female   74
8       Biron      Acklands        backlandss@comsenz.com    Male   13
28  Zachariah         Meins          zmeins2h@weather.com    Male   69
19      Ambur        Aickin           aaickin1x@about.com    Male   60
29      Judas        Maffin         jmaffin2i@dropbox.com    Male    3
30     Sheree        Cockin     scockin2l@accuweather.com  Female   94
31     Kattie       Claxson        kclaxson2o@booking.com  Female   18
24       Alex         Darth    adarth28@ezinearticles.com  Female   98
23     Rudolf        Kalewe           rkalewe24@fotki.com    Male   12
6         Ray         Padly           rpadlyl@twitpic.com    Male   85

In [ ]:
df.sample(10,replace=True)

   first_name  last_name                       email  gender  age
8       Biron   Acklands      backlandss@comsenz.com    Male   13
24       Alex      Darth  adarth28@ezinearticles.com  Female   98
30     Sheree     Cockin   scockin2l@accuweather.com  Female   94
0     Pietrek    Scanlin      pscanlin1@yolasite.com    Male   91
2       David   Meredyth  dmeredyth9@telegraph.co.uk  Female   68
12       Bili  Swetenham      bswetenham16@europa.eu    Male   23
29      Judas     Maffin       jmaffin2i@dropbox.com    Male    3
26      Peder     Murrie     pmurrie2e@bloglovin.com    Male   69
3   Raffaello  Firminger   rfirmingerb@bloomberg.com  Female   74
3   Raffaello  Firminger   rfirmingerb@bloomberg.com  Female   74