In [1]:
import numpy as np
import pandas as pd
import sqlite3 as sql

***# Creating, Writing, Editing***

In [3]:
db = sql.connect('world_info')
cursor = db.cursor()

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/Electricity_Production_By_Source.csv")
df

,Entity,Code,Year,Electricity from coal (TWh),Electricity from gas (TWh),Electricity from hydro (TWh),Electricity from other renewables (TWh),Electricity from solar (TWh),Electricity from oil (TWh),Electricity from wind (TWh),Electricity from nuclear (TWh)
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [6]:
cols = ['entity', 'code', 'year', 'coal', 'gas', 'hydro','other', 'solar', 'oil', 'wind', 'nuclear']
df.columns = cols
df

,entity,code,year,coal,gas,hydro,other,solar,oil,wind,nuclear
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [7]:
df.to_sql('electr', db)

6241

In [12]:
query = "SELECT * FROM electr"
cursor.execute(query)
df2 = pd.read_sql(query,db, index_col="index")

In [13]:
df2

,entity,code,year,coal,gas,hydro,other,solar,oil,wind,nuclear
index,,,,,,,,,,,
0,Afghanistan,AFG,2000,0.000000,0.155,0.312,0.000000,0.000,0.0,0.0,0.0
1,Afghanistan,AFG,2001,0.000000,0.094,0.498,0.000000,0.000,0.0,0.0,0.0
2,Afghanistan,AFG,2002,0.000000,0.132,0.555,0.000000,0.000,0.0,0.0,0.0
3,Afghanistan,AFG,2003,0.000000,0.309,0.630,0.000000,0.000,0.0,0.0,0.0
4,Afghanistan,AFG,2004,0.000000,0.329,0.565,0.000000,0.000,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
6236,Zimbabwe,ZWE,2015,4.311780,0.000,4.940,0.128000,0.008,0.0,0.0,0.0
6237,Zimbabwe,ZWE,2016,3.714880,0.000,2.955,0.147000,0.009,0.0,0.0,0.0
6238,Zimbabwe,ZWE,2017,3.218560,0.000,3.929,0.151000,0.011,0.0,0.0,0.0
6239,Zimbabwe,ZWE,2018,3.932020,0.000,5.000,0.187000,0.014,0.0,0.0,0.0
6240,Zimbabwe,ZWE,2019,3.805433,0.000,5.020,0.206667,0.014,0.0,0.0,0.0

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6241 entries, 0 to 6240
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   entity   6241 non-null   object
 1   code     5474 non-null   object
 2   year     6241 non-null   int64
 3   coal     5221 non-null   float64
 4   gas      5221 non-null   float64
 5   hydro    6241 non-null   float64
 6   other    6206 non-null   float64
 7   solar    6241 non-null   float64
 8   oil      5221 non-null   float64
 9   wind     6241 non-null   float64
 10  nuclear  6241 non-null   float64
dtypes: float64(8), int64(1), object(2)
memory usage: 585.1+ KB

# Open new table

In [18]:
query = """CREATE TABLE IF NOT EXISTS population(
rank INT,
country TEXT PRIMARY KEY,
density DOUBLE,
population DOUBLE NOT NULL,
area INT NOT NULL
)"""
cursor.execute(query)
db.commit()

In [21]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('electr',), ('population',)]

In [22]:
cursor.execute("PRAGMA table_info(population);")
cursor.fetchall()

[(0, 'rank', 'INT', 0, None, 0),
 (1, 'country', 'TEXT', 0, None, 1),
 (2, 'density', 'DOUBLE', 0, None, 0),
 (3, 'population', 'DOUBLE', 1, None, 0),
 (4, 'area', 'INT', 1, None, 0)]

In [23]:
query = "SELECT * FROM population"
df3 = pd.read_sql(query,db)
df3

Empty DataFrame
Columns: [rank, country, density, population, area]
Index: []

In [26]:
q = """ CREATE TABLE IF NOT EXISTS cars(
  rank INT,
  brand TEXT NOT NULL,
  price INT,
  model TEXT PRIMARY KEY,
  year INT,
  mileage INT NOT NULL
)
"""
cursor.execute(q)
db.commit()

In [28]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
cursor.fetchall()

[('electr',), ('population',), ('cars',)]

In [33]:
q = "INSERT INTO cars VALUES(1, 'toyota', 6300, 'cruiser', 2008, 274177)"
cursor.execute(q)

In [34]:
q_1 = 'SELECT * FROM cars'
cursor.execute(q_1)
cursor.fetchall()

[(1, 'toyota', 6300, 'cruiser', 2008, 274177)]

In [35]:
pd.read_sql(q_1,db)

   rank   brand  price    model  year  mileage
0     1  toyota   6300  cruiser  2008   274177

In [37]:
query = """
INSERT INTO cars (brand,model,mileage)
VALUES ('chevrolet', 'cobalt', 4243)
"""
cursor.execute(query)
db.commit()

In [38]:
q_1 = 'SELECT * FROM cars'
cursor.execute(q_1)
cursor.fetchall()

[(1, 'toyota', 6300, 'cruiser', 2008, 274177),
 (None, 'chevrolet', None, 'cobalt', None, 4243)]

In [39]:
pd.read_sql(q_1,db)

   rank      brand   price    model    year  mileage
0   1.0     toyota  6300.0  cruiser  2008.0   274177
1   NaN  chevrolet     NaN   cobalt     NaN     4243

In [40]:
query = """
UPDATE cars
SET rank = 2, price = 11000, year = 2019
WHERE brand = 'chevrolet'
"""
cursor.execute(query)
db.commit()

In [41]:
cursor.execute(q_1)
cursor.fetchall()

[(1, 'toyota', 6300, 'cruiser', 2008, 274177),
 (2, 'chevrolet', 11000, 'cobalt', 2019, 4243)]

In [42]:
pd.read_sql(q_1,db)

   rank      brand  price    model  year  mileage
0     1     toyota   6300  cruiser  2008   274177
1     2  chevrolet  11000   cobalt  2019     4243

In [44]:
# Deleting
query = 'DELETE FROM cars WHERE brand="toyota"'
cursor.execute(query)
db.commit()

In [45]:
query = "SELECT * FROM cars"
cursor.execute(query)
cursor.fetchall()

[(2, 'chevrolet', 11000, 'cobalt', 2019, 4243)]

In [47]:
cursor.execute('DROP TABLE cars')
db.commit()

In [51]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")
cursor.fetchall()

[('electr',), ('population',)]

In [52]:
db.close()